name: Run Feed Curator

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-feed-curator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Specify Python 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npx playwright install  # Add this line to install Playwright browsers

      - name: Run Feed Curator
        run: |
          python feed_curator.py
